# Generated by Django 3.2.9 on 2022-01-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
