# Generated by Django 3.2.9 on 2022-01-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(default='Mumbai', max_length=50),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(default='EV Station', max_length=100),
        ),
    ]
