# Generated by Django 3.2.9 on 2022-02-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='plug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Plug', to='booking.plug'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plug_type',
            field=models.CharField(choices=[('IEC-60309', 'IEC-60309'), ('IEC-62196(AC type 2)', 'IEC-62196(AC type 2)'), ('3 Pin Connector(15 Amp)', '3 Pin Connector(15 Amp)'), ('CSS connector', 'CSS connector'), ('GBT connector', 'GBT connector'), ('CHAdeMO connector', 'CHAdeMO connector')], default='IEC-62196(AC type 2)', max_length=25),
        ),
    ]
