# Generated by Django 3.2.9 on 2022-02-23 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20220214_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='units',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='plug',
            name='booking_status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='plug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Booking_Plug', to='booking.plug'),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('booking_status', models.BooleanField(default=False)),
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Plug', to='booking.plug')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Slot', to='booking.slot'),
        ),
    ]
