# Generated by Django 3.2.8 on 2021-11-29 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20211129_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='plug',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plug',
            name='charger_type',
            field=models.CharField(choices=[('IEC-60309', 'IEC-60309'), ('IEC-62196(AC type 2)', 'IEC-62196(AC type 2)'), ('3 Pin Connector(15 Amp)', '3 Pin Connector(15 Amp)'), ('CSS connector', 'CSS connector'), ('GBT connector', 'GBT connector'), ('CHAdeMO connector', 'CHAdeMO connector')], default='IEC-62196(AC type 2)', max_length=25),
        ),
        migrations.AddField(
            model_name='plug',
            name='charging_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plug',
            name='charging_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plug',
            name='station_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.station'),
        ),
        migrations.AddField(
            model_name='review',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.station'),
        ),
        migrations.AddField(
            model_name='review',
            name='feedback',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='written_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='station',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='station',
            name='location',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='station',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='photos',
            field=models.ImageField(blank=True, upload_to='stations/'),
        ),
        migrations.AddField(
            model_name='station',
            name='star_rating',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='station',
            name='station_name',
            field=models.CharField(default='EV Station', max_length=20),
        ),
        migrations.AddField(
            model_name='station',
            name='working_hours',
            field=models.CharField(default='9:00 am to 11:00 pm', max_length=20),
        ),
    ]
