# Generated by Django 3.2.9 on 2022-02-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20220223_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Slot', to='booking.slot'),
            preserve_default=False,
        ),
    ]
