# Generated by Django 3.2.9 on 2022-02-24 05:39

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='photos',
            field=models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='stations/'),
        ),
    ]
