# Generated by Django 3.2.8 on 2021-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='star_rating',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
