# Generated by Django 3.2.9 on 2021-12-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_payment_of_payment_booking_id'),
        ('booking', '0007_alter_station_star_rating'),
    ]

    operations = [
    ]
