# Generated by Django 3.2.9 on 2021-12-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_merge_20211203_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='booking_id',
            new_name='payment_of',
        ),
    ]
